import { AUDIT_EVENT } from '../../constants/audit-events';

/** High-signal events for Super Admin activity view */
export const SUPER_ADMIN_AUDIT_EVENT_WHITELIST = [
  AUDIT_EVENT.TENANT_CREATED,
  AUDIT_EVENT.TENANT_UPDATED,
  AUDIT_EVENT.TENANT_ACTIVATED,
  AUDIT_EVENT.TENANT_DEACTIVATED,
  AUDIT_EVENT.SCHOOL_ADMIN_ASSIGNED,
  AUDIT_EVENT.STAFF_INVITE_CREATED,
  AUDIT_EVENT.SUBSCRIPTION_UPDATED,
  AUDIT_EVENT.SYSTEM_ANNOUNCEMENT_CREATED,
  AUDIT_EVENT.SYSTEM_ANNOUNCEMENT_UPDATED,
  AUDIT_EVENT.GOV_AUDITOR_CREATED,
  AUDIT_EVENT.GOV_AUDITOR_UPDATED,
  AUDIT_EVENT.GOV_AUDITOR_SCOPE_ASSIGNED,
  AUDIT_EVENT.GOV_AUDITOR_SCOPE_UPDATED,
] as const;
